# Generated by Django 3.0.2 on 2020-02-17 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('slug', models.SlugField(help_text='a user friendly url', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=150)),
                ('section', models.CharField(blank=True, choices=[('GA', 'General Ability'), ('MATH', 'Mathematics'), ('none', 'None')], max_length=30, null=True)),
                ('quiz', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='studyroom.Quiz', verbose_name='Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(help_text='Enter the answer text that you want to displayed', max_length=200, verbose_name='Content')),
                ('active', models.BooleanField(default=True, help_text='is this a active answer?', verbose_name='Active')),
                ('correct', models.BooleanField(default=False, help_text='Is this a correct answer?', verbose_name='Correct')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studyroom.Question')),
            ],
        ),
    ]
