# Generated by Django 3.0.2 on 2020-03-07 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0002_studentanswer_takenquiz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takenquiz',
            name='question',
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_question',
            field=models.PositiveIntegerField(blank=True, help_text='Number of questions to be answered on each attempt.', null=True, verbose_name='Max Questions'),
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='curr_question',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='questions',
            field=models.TextField(null=True),
        ),
    ]
