# Generated by Django 3.0.2 on 2020-03-07 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0003_auto_20200307_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takenquiz',
            old_name='std',
            new_name='student',
        ),
    ]
