# Generated by Django 3.0.2 on 2020-03-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0004_auto_20200307_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takenquiz',
            name='answer',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='takenquiz',
            name='correct',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='takenquiz',
            name='curr_question',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
