# Generated by Django 3.0.2 on 2020-03-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyroom', '0005_auto_20200307_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='takenquiz',
            old_name='date',
            new_name='created_date',
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='takenquiz',
            name='completed_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
